CREATE TABLE IF NOT EXISTS announcements (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  body TEXT NOT NULL,
  category VARCHAR(50) DEFAULT 'General',
  author VARCHAR(100) DEFAULT 'Admin',
  is_published BOOLEAN DEFAULT TRUE,
  published_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_ann_published (is_published, published_at)
);

CREATE TABLE IF NOT EXISTS news (
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  excerpt VARCHAR(500) NULL,
  content TEXT NOT NULL,
  image_url VARCHAR(255) NULL,
  category VARCHAR(50) DEFAULT 'General',
  author VARCHAR(100) DEFAULT 'Admin',
  is_published BOOLEAN DEFAULT TRUE,
  published_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_news_published (is_published, published_at)
);

