CREATE TABLE IF NOT EXISTS approved_applicants (
    id INT PRIMARY KEY AUTO_INCREMENT,
    serial_number VARCHAR(50) NOT NULL,
    title VARCHAR(10),
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50),
    last_name VARCHAR(50) NOT NULL,
    dob DATE NOT NULL,
    gender VARCHAR(10) NOT NULL,
    place_of_birth VARCHAR(100) NOT NULL,
    birth_region VARCHAR(50) NOT NULL,
    nationality VARCHAR(50) NOT NULL,
    residence VARCHAR(100) NOT NULL,
    residence_region VARCHAR(50) NOT NULL,
    religion VARCHAR(50),
    languages JSON,
    id_type VARCHAR(50) NOT NULL,
    id_number VARCHAR(50) NOT NULL,
    id_document_path VARCHAR(255),
    photo_path VARCHAR(255),
    address TEXT NOT NULL,
    city VARCHAR(100) NOT NULL,
    region VARCHAR(50) NOT NULL,
    district VARCHAR(100),
    country VARCHAR(50) NOT NULL,
    phone JSON,
    gps_code VARCHAR(20),
    email VARCHAR(100) NOT NULL,
    core_subjects JSON NOT NULL,
    core_index_numbers JSON NOT NULL,
    core_grades JSON NOT NULL,
    elective_subjects JSON NOT NULL,
    elective_index_numbers JSON NOT NULL,
    elective_grades JSON NOT NULL,
    certificates_path JSON,
    parent1_name VARCHAR(100) NOT NULL,
    parent1_relation VARCHAR(50) NOT NULL,
    parent1_occupation VARCHAR(100) NOT NULL,
    parent1_phone VARCHAR(20) NOT NULL,
    parent1_email VARCHAR(100) NOT NULL,
    parent2_name VARCHAR(100),
    parent2_relation VARCHAR(50),
    parent2_occupation VARCHAR(100),
    parent2_phone VARCHAR(20),
    parent2_email VARCHAR(100),
    emergency_contact VARCHAR(100) NOT NULL,
    emergency_phone VARCHAR(20) NOT NULL,
    emergency_relation VARCHAR(50) NOT NULL,
    disability_status ENUM('yes', 'no') NOT NULL,
    disability_type VARCHAR(100),
    hear_about VARCHAR(50),
    question TEXT,
    status ENUM('pending', 'approved', 'rejected') DEFAULT 'approved',
    approved_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    approved_by VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
); 